requires "Kossy", 0.19;
requires "DBIx::Sunny";
requires "JSON::XS";
requires "Digest::SHA";
requires "File::Temp";
requires "Time::Piece";

requires "DBD::mysql";
requires "Starlet";
requires "Plack::Session";
requires "Data::Dumper";
requires "Plack::Middleware::AxsLog"